#!/bin/bash
# Copyright 2016 Alf Gaida <agaida@siduction.org>
# License: WTFPL-2

git checkout template -- template
git checkout template -- bootstrap

# ./bootstrap
# ./bootstrap

# rm -rf template
# rm -f bootstrap

# git add .
